### ISSUE TITLE
step_registry workflow failure fails the CI job

### ISSUE THREAD

**Issue by vimalk78** [openshift/release#14124]
/kind question

CI Operator Step Registry

/area test-execution

## What did you expect to happen?

A gather step failed
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-logging-operator/830/pull-ci-openshift-cluster-logging-operator-master-functional/1335603863574548480
this failed the job. gather step failure/timeout when the tests have passed should not fail the job.

## What happened?

The job seemed to have failed when a gather step failed

## How can the error be reproduced?

run cluster-logging-operator job

## Is there anything else we need to know?
No

**Comment by vimalk78** [comment]
adding raw logs in case the link disappears

```
2020/12/06 15:15:55 ci-operator version v20201205-32c093e
2020/12/06 15:15:55 Loading configuration from https://config.ci.openshift.org for openshift/cluster-logging-operator@master
2020/12/06 15:15:55 Resolved source https://github.com/openshift/cluster-logging-operator to master@81cf04c9, merging: #830 eb34dbea @eranra
2020/12/06 15:15:55 Resolved openshift/release:golang-1.14 to sha256:aaebd928d43e3c3b465593b21ed2ab276020965d8ff3b5913274b7e89bc9182d
2020/12/06 15:15:55 Resolved openshift/release:golang-1.13 to sha256:cace1b5155235ca716729bf96d037779e5f2c982afb61de179b712d1bf65f064
2020/12/06 15:15:55 Resolved openshift/release:golang-1.14 to sha256:aaebd928d43e3c3b465593b21ed2ab276020965d8ff3b5913274b7e89bc9182d
2020/12/06 15:15:55 Resolved ocp/4.7:cli to sha256:eddfbc2ba3e7cacfd0f2a04e58be8d03dd59a9226d4cdacde5f15b2924bbc4c7
2020/12/06 15:15:55 Resolved ocp/builder:rhel-8-golang-1.15-openshift-4.7 to sha256:ab57072dbfe9df6e06c6f4313a6b01b9f14e749d7eec6d0ae56e208f3bf22cd3
2020/12/06 15:15:55 Resolved ocp/4.7:cli to sha256:eddfbc2ba3e7cacfd0f2a04e58be8d03dd59a9226d4cdacde5f15b2924bbc4c7
2020/12/06 15:15:55 Resolved ocp/builder:rhel-8-golang-1.15-openshift-4.6 to sha256:509e41732e49864d2b5d4bf32a02a0670c9943582d10f3c0963b7597a368d0bf
2020/12/06 15:15:55 Resolved ocp/builder:rhel-8-golang-openshift-4.6 to sha256:4bab331549afeb091bbdba52ddb215a19a6d02c005d97cc4917bd3a109732eca
2020/12/06 15:15:55 Resolved ocp/4.7:base to sha256:28ca83fc231a7ed11a3cf5a3be7574f867b84455890a6389e15fc14c84621283
2020/12/06 15:15:55 Resolved ocp/4.7:elasticsearch-operator-src to sha256:e8bb6fc0630d0d595f7cfe1d44fbe94ae58c0c74881c46128e560e7b1496a91a
2020/12/06 15:15:55 Resolved origin/centos:8 to sha256:fc4a234b91cc4b542bac8a6ad23b2ddcee60ae68fc4dbd4a52efb5f1b0baad71
2020/12/06 15:15:55 Resolved origin/centos:8 to sha256:fc4a234b91cc4b542bac8a6ad23b2ddcee60ae68fc4dbd4a52efb5f1b0baad71
2020/12/06 15:15:56 Resolved ocp/cli-jq:latest to sha256:03e6a8145c85cb86739017a9b2c1b244e81eeddc77ffe102c21ef3982aec162f
2020/12/06 15:15:56 Resolved ocp/4.5:upi-installer to sha256:bf6e65c1283d51dcd8a4d343ef715fcb60b5fbad767b1e2b1c9c701db5ad4846
2020/12/06 15:15:56 Resolved origin/centos:8 to sha256:fc4a234b91cc4b542bac8a6ad23b2ddcee60ae68fc4dbd4a52efb5f1b0baad71
2020/12/06 15:15:56 Resolved origin/centos:8 to sha256:fc4a234b91cc4b542bac8a6ad23b2ddcee60ae68fc4dbd4a52efb5f1b0baad71
2020/12/06 15:15:56 Resolved ocp/cli-jq:latest to sha256:03e6a8145c85cb86739017a9b2c1b244e81eeddc77ffe102c21ef3982aec162f
2020/12/06 15:15:57 Resolved ocp/4.5:upi-installer to sha256:bf6e65c1283d51dcd8a4d343ef715fcb60b5fbad767b1e2b1c9c701db5ad4846
2020/12/06 15:15:57 Using namespace https://console.build01.ci.openshift.org/k8s/cluster/projects/ci-op-9xx7i0kc
2020/12/06 15:15:57 Running [input:root], [input:ocp_4.7_cli], [input:ocp_builder_rhel-8-golang-1.15-openshift-4.7], [input:base], [input:elasticsearch-operator-src], [release-inputs], [input:origin-centos-8], [input:origin-centos-8], [input:ocp-cli-jq-latest], [input:ocp-4.5-upi-installer], [input:origin-centos-8], [input:origin-centos-8], [input:ocp-cli-jq-latest], [input:ocp-4.5-upi-installer], src, cluster-logging-operator, cluster-logging-operator-registry, cluster-logging-operator-e2e, [output:stable:cluster-logging-operator], [output:stable:cluster-logging-operator-registry], [output:stable:cluster-logging-operator-e2e], functional, [images], [release:latest]
2020/12/06 15:15:57 Creating namespace ci-op-9xx7i0kc
2020/12/06 15:15:57 Creating rolebinding for user eranra in namespace ci-op-9xx7i0kc
2020/12/06 15:15:57 Setting up pipeline imagestream for the test
2020/12/06 15:15:57 Created secret functional-cluster-profile
2020/12/06 15:15:57 Created PDB for pods with openshift.io/build.name label
2020/12/06 15:15:57 Created PDB for pods with created-by-ci label
2020/12/06 15:15:57 Tagging ocp/4.5:upi-installer into pipeline:ocp-4.5-upi-installer
2020/12/06 15:15:57 Tagging ocp/4.7:elasticsearch-operator-src into pipeline:elasticsearch-operator-src
2020/12/06 15:15:57 Tagging ocp/cli-jq:latest into pipeline:ocp-cli-jq-latest
2020/12/06 15:15:57 Tagging openshift/release:golang-1.14 into pipeline:root
2020/12/06 15:15:57 Tagging origin/centos:8 into pipeline:origin-centos-8
2020/12/06 15:15:57 Tagging ocp/4.5:upi-installer into pipeline:ocp-4.5-upi-installer
2020/12/06 15:15:57 Tagging ocp/4.7:base into pipeline:base
2020/12/06 15:15:57 Tagging origin/centos:8 into pipeline:origin-centos-8
2020/12/06 15:15:57 Tagging ocp/cli-jq:latest into pipeline:ocp-cli-jq-latest
2020/12/06 15:15:57 Tagging ocp/4.7:cli into pipeline:ocp_4.7_cli
2020/12/06 15:15:57 Tagging origin/centos:8 into pipeline:origin-centos-8
2020/12/06 15:15:57 Tagging ocp/builder:rhel-8-golang-1.15-openshift-4.7 into pipeline:ocp_builder_rhel-8-golang-1.15-openshift-4.7
2020/12/06 15:15:57 Tagging origin/centos:8 into pipeline:origin-centos-8
2020/12/06 15:15:57 Tagged shared images from ocp/4.7:${component}, images will be pullable from registry.build01.ci.openshift.org/ci-op-9xx7i0kc/stable:${component}
I1206 15:15:58.549952      13 request.go:645] Throttling request took 1.031106533s, request: POST:https://172.30.0.1:443/apis/image.openshift.io/v1/namespaces/ci-op-9xx7i0kc/imagestreamtags
2020/12/06 15:15:59 Building src
2020/12/06 15:17:10 Build src succeeded after 1m9s
2020/12/06 15:17:10 Building cluster-logging-operator-e2e
2020/12/06 15:17:10 Building cluster-logging-operator
2020/12/06 15:17:10 Building cluster-logging-operator-registry
2020/12/06 15:18:30 Build cluster-logging-operator-e2e succeeded after 1m19s
2020/12/06 15:18:30 Tagging cluster-logging-operator-e2e into stable
2020/12/06 15:18:50 Build cluster-logging-operator-registry succeeded after 1m36s
2020/12/06 15:18:50 Tagging cluster-logging-operator-registry into stable
2020/12/06 15:20:00 Build cluster-logging-operator succeeded after 2m49s
2020/12/06 15:20:00 Tagging cluster-logging-operator into stable
2020/12/06 15:20:00 Create release image registry.build01.ci.openshift.org/ci-op-9xx7i0kc/release:latest
2020/12/06 15:20:00 Executing pod "release-latest"
2020/12/06 15:20:26 Copied 4.16MB of artifacts from release-latest to /logs/artifacts/release-latest
2020/12/06 15:20:26 Acquiring leases for "functional"
2020/12/06 15:20:26 Acquiring 1 lease(s) for "aws-quota-slice"
2020/12/06 15:20:26 Acquired lease(s) [d53e754a-a1a8-4f43-9b60-094fcc754e19] for "aws-quota-slice"
2020/12/06 15:20:26 Creating multi-stage test secret "functional"
2020/12/06 15:20:26 Creating multi-stage test credentials for "functional"
2020/12/06 15:21:26 Executing pod "functional-ipi-install-hosted-loki"
2020/12/06 15:21:31 Container cp-secret-wrapper in pod functional-ipi-install-hosted-loki completed successfully
2020/12/06 15:21:36 Container test in pod functional-ipi-install-hosted-loki completed successfully
2020/12/06 15:21:36 Pod functional-ipi-install-hosted-loki succeeded after 5s
2020/12/06 15:21:37 Executing pod "functional-ipi-conf"
2020/12/06 15:21:42 Container cp-secret-wrapper in pod functional-ipi-conf completed successfully
2020/12/06 15:21:47 Container test in pod functional-ipi-conf completed successfully
2020/12/06 15:21:47 Pod functional-ipi-conf succeeded after 5s
2020/12/06 15:21:47 Executing pod "functional-ipi-conf-aws"
2020/12/06 15:21:52 Container cp-secret-wrapper in pod functional-ipi-conf-aws completed successfully
2020/12/06 15:21:57 Container test in pod functional-ipi-conf-aws completed successfully
2020/12/06 15:21:57 Pod functional-ipi-conf-aws succeeded after 5s
2020/12/06 15:22:02 Executing pod "functional-ipi-install-rbac"
2020/12/06 15:22:12 Container cp-secret-wrapper in pod functional-ipi-install-rbac completed successfully
2020/12/06 15:22:12 Container test in pod functional-ipi-install-rbac completed successfully
2020/12/06 15:22:12 Pod functional-ipi-install-rbac succeeded after 8s
2020/12/06 15:22:12 Executing pod "functional-ipi-install-install"
2020/12/06 15:22:17 Container cp-secret-wrapper in pod functional-ipi-install-install completed successfully
2020/12/06 15:52:57 Container test in pod functional-ipi-install-install completed successfully
2020/12/06 15:52:57 Pod functional-ipi-install-install succeeded after 30m43s
2020/12/06 15:52:58 Copied 3.00MB of artifacts from functional-ipi-install-install to /logs/artifacts/functional/ipi-install-install
2020/12/06 15:52:58 Executing pod "functional-test"
2020/12/06 15:53:03 Container cp-secret-wrapper in pod functional-test completed successfully
2020/12/06 15:53:08 Container inject-cli in pod functional-test completed successfully
2020/12/06 15:54:38 Container test in pod functional-test completed successfully
2020/12/06 15:54:38 Pod functional-test succeeded after 1m36s
2020/12/06 15:54:38 Executing pod "functional-gather-hosted-loki" with activeDeadlineSeconds=1800
2020/12/06 15:54:43 Container cp-secret-wrapper in pod functional-gather-hosted-loki completed successfully
2020/12/06 16:24:43 error: unable to retrieve artifacts from pod functional-gather-hosted-loki: could not read gzipped artifacts: unable to upgrade connection: container not found ("artifacts")
2020/12/06 16:24:43 Executing pod "functional-gather-aws-console"
2020/12/06 16:24:44 error: unable to retrieve artifacts from pod functional-gather-hosted-loki: could not read gzipped artifacts: unable to upgrade connection: container not found ("artifacts")
Pod functional-gather-hosted-loki found in map: false, channel nil: true
goroutine 1668 [running]:
runtime/debug.Stack(0x49, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/openshift/ci-tools/pkg/steps.(*ArtifactWorker).run(0xc000e0d800)
	/go/src/github.com/openshift/ci-tools/pkg/steps/artifacts.go:445 +0x2ca
created by github.com/openshift/ci-tools/pkg/steps.NewArtifactWorker
	/go/src/github.com/openshift/ci-tools/pkg/steps/artifacts.go:430 +0x145
2020/12/06 16:24:44 error: unable to retrieve artifacts from pod functional-gather-hosted-loki: could not read gzipped artifacts: unable to upgrade connection: container not found ("artifacts")
Pod functional-gather-hosted-loki found in map: false, channel nil: true
goroutine 1668 [running]:
runtime/debug.Stack(0x49, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/openshift/ci-tools/pkg/steps.(*ArtifactWorker).run(0xc000e0d800)
	/go/src/github.com/openshift/ci-tools/pkg/steps/artifacts.go:445 +0x2ca
created by github.com/openshift/ci-tools/pkg/steps.NewArtifactWorker
	/go/src/github.com/openshift/ci-tools/pkg/steps/artifacts.go:430 +0x145
2020/12/06 16:24:45 error: unable to retrieve artifacts from pod functional-gather-hosted-loki: could not read gzipped artifacts: unable to upgrade connection: container not found ("artifacts")
Pod functional-gather-hosted-loki found in map: false, channel nil: true
goroutine 1668 [running]:
runtime/debug.Stack(0x49, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/openshift/ci-tools/pkg/steps.(*ArtifactWorker).run(0xc000e0d800)
	/go/src/github.com/openshift/ci-tools/pkg/steps/artifacts.go:445 +0x2ca
created by github.com/openshift/ci-tools/pkg/steps.NewArtifactWorker
	/go/src/github.com/openshift/ci-tools/pkg/steps/artifacts.go:430 +0x145
2020/12/06 16:24:45 error: unable to retrieve artifacts from pod functional-gather-hosted-loki: could not read gzipped artifacts: unable to upgrade connection: container not found ("artifacts")
Pod functional-gather-hosted-loki found in map: false, channel nil: true
goroutine 1668 [running]:
runtime/debug.Stack(0x49, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/openshift/ci-tools/pkg/steps.(*ArtifactWorker).run(0xc000e0d800)
	/go/src/github.com/openshift/ci-tools/pkg/steps/artifacts.go:445 +0x2ca
created by github.com/openshift/ci-tools/pkg/steps.NewArtifactWorker
	/go/src/github.com/openshift/ci-tools/pkg/steps/artifacts.go:430 +0x145
2020/12/06 16:24:45 error: unable to retrieve artifacts from pod functional-gather-hosted-loki: could not read gzipped artifacts: unable to upgrade connection: container not found ("artifacts")
Pod functional-gather-hosted-loki found in map: false, channel nil: true
goroutine 1668 [running]:
runtime/debug.Stack(0x49, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/openshift/ci-tools/pkg/steps.(*ArtifactWorker).run(0xc000e0d800)
	/go/src/github.com/openshift/ci-tools/pkg/steps/artifacts.go:445 +0x2ca
created by github.com/openshift/ci-tools/pkg/steps.NewArtifactWorker
	/go/src/github.com/openshift/ci-tools/pkg/steps/artifacts.go:430 +0x145
2020/12/06 16:24:49 Container cp-secret-wrapper in pod functional-gather-aws-console completed successfully
2020/12/06 16:24:54 Container test in pod functional-gather-aws-console completed successfully
2020/12/06 16:24:54 Pod functional-gather-aws-console succeeded after 10s
2020/12/06 16:24:54 Executing pod "functional-gather-must-gather"
2020/12/06 16:24:59 Container cp-secret-wrapper in pod functional-gather-must-gather completed successfully
2020/12/06 16:26:34 Container test in pod functional-gather-must-gather completed successfully
2020/12/06 16:26:34 Pod functional-gather-must-gather succeeded after 1m36s
2020/12/06 16:26:35 Copied 11.10MB of artifacts from functional-gather-must-gather to /logs/artifacts/functional/gather-must-gather
2020/12/06 16:26:35 Executing pod "functional-gather-extra"
2020/12/06 16:26:40 Container cp-secret-wrapper in pod functional-gather-extra completed successfully
2020/12/06 16:27:15 Container test in pod functional-gather-extra completed successfully
2020/12/06 16:27:15 Pod functional-gather-extra succeeded after 35s
2020/12/06 16:27:20 Copied 91.10MB of artifacts from functional-gather-extra to /logs/artifacts/functional/gather-extra
2020/12/06 16:27:20 Executing pod "functional-gather-audit-logs"
2020/12/06 16:27:25 Container cp-secret-wrapper in pod functional-gather-audit-logs completed successfully
2020/12/06 16:27:40 Container test in pod functional-gather-audit-logs completed successfully
2020/12/06 16:27:40 Pod functional-gather-audit-logs succeeded after 16s
2020/12/06 16:27:42 Copied 27.73MB of artifacts from functional-gather-audit-logs to /logs/artifacts/functional/gather-audit-logs
2020/12/06 16:27:42 Executing pod "functional-ipi-deprovision-deprovision"
2020/12/06 16:27:47 Container cp-secret-wrapper in pod functional-ipi-deprovision-deprovision completed successfully
2020/12/06 16:31:17 Container test in pod functional-ipi-deprovision-deprovision completed successfully
2020/12/06 16:31:17 Pod functional-ipi-deprovision-deprovision succeeded after 3m33s
2020/12/06 16:31:17 Releasing leases for "functional"
2020/12/06 16:31:17 Releasing lease d53e754a-a1a8-4f43-9b60-094fcc754e19 for "aws-quota-slice"
2020/12/06 16:31:17 No custom metadata found and prow metadata already exists. Not updating the metadata.
2020/12/06 16:31:18 Ran for 1h15m22s
error: some steps failed:
  * could not run steps: step functional failed: "functional" post steps failed: "functional" pod "functional-gather-hosted-loki" exceeded the configured timeout activeDeadlineSeconds=1800: the pod ci-op-9xx7i0kc/functional-gather-hosted-loki failed after 30m5s (failed containers: ): DeadlineExceeded Pod was active on the node longer than the specified deadline
Link to step on registry info site: https://steps.ci.openshift.org/reference/gather-hosted-loki
Link to job on registry info site: https://steps.ci.openshift.org/job?org=openshift&repo=cluster-logging-operator&branch=master&test=functional
time="2020-12-06T16:31:18Z" level=info msg="Reporting job state 'failed' with reason 'executing_graph:step_failed:utilizing_lease:executing_test:executing_multi_stage_test'"
```
