### ISSUE TITLE
config updater panic

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1978]
```
{"author":"kargakis","level":"info","msg":"cloning openshift/release","org":"openshift","plugin":"config-updater","pr":1977,"repo":"release","time":"2018-10-19T18:58:03Z","url":"https://github.com/openshift/release/pull/1977"}
2018/10/19 18:58:03 http: panic serving 172.16.8.78:46754: runtime error: invalid memory address or nil pointer dereference
goroutine 259 [running]:
net/http.(*conn).serve.func1(0xc000442640)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0xd35cc0, 0x15cb1c0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
k8s.io/test-infra/prow/git.(*Client).getCredentials(0xc000206800, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/test-infra/prow/git/git.go:109 +0x76
k8s.io/test-infra/prow/git.(*Client).Clone(0xc000206800, 0xc0005a2020, 0x11, 0x0, 0x0, 0x0)
	/go/src/k8s.io/test-infra/prow/git/git.go:139 +0xe4
main.(*Server).handleEvent(0xc000263b60, 0xc0004f6300, 0xc, 0xc0001dc1e0, 0x24, 0xc00049c000, 0x629b, 0x7e00, 0x0, 0x0)
	/go/src/k8s.io/test-infra/experiment/config-updater/server.go:156 +0xa5c
main.(*Server).ServeHTTP(0xc000263b60, 0xf67c80, 0xc00040c460, 0xc00026a100)
	/go/src/k8s.io/test-infra/experiment/config-updater/server.go:112 +0x1db
net/http.(*ServeMux).ServeHTTP(0x15e0020, 0xf67c80, 0xc00040c460, 0xc00026a100)
	/usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0002969c0, 0xf67c80, 0xc00040c460, 0xc00026a100)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000442640, 0xf699c0, 0xc000310440)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```
This is from the config updater we run in the azure namespace.

/sig azure
/kind bug

**Comment by kargakis** [comment]
Happens in the ci config-updater too
/remove-sig azure
