### ISSUE TITLE
Jenkins master running out of disk space

### ISSUE THREAD

**Issue by kargakis** [openshift/release#346]
I tried to login earlier and I was getting a stacktrace with a message saying there was no space left in the device. Looking in the jenkins log, I see a bunch of 
```
SEVERE: Failed to load initial Builds: java.lang.NullPointerException
java.lang.NullPointerException
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$2.compare(BuildWatcher.java:164)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$2.compare(BuildWatcher.java:159)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher.onInitialBuilds(BuildWatcher.java:159)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$1.doRun(BuildWatcher.java:98)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Seems to have fixed itself now. The jenkins log goes back until ~last midnight and seems that we had faulty behavior at least since then.

@stevekuznetsov @csrwng

**Comment by kargakis** [comment]
Things seem to started breaking today around 01:00 UTC

https://deck-ci.svc.ci.openshift.org/?job=origin-ci-ut-origin

**Comment by kargakis** [comment]
Ok, this seems to recur non-deterministically

I see it again now:
```
java.io.IOException: Failed to create a temporary file in /var/lib/jenkins/users/kargakis-admin
<- snip ->
Caused by: java.io.IOException: No space left on device
```

**Comment by stevekuznetsov** [comment]
Classic Jenkins storage issues ... looking into where the storage is used right now, but we should follow what we have in ci.openshift by nuking workspaces and not keeping around old builds. /cc @dobbymoodge may have more fun facts

**Comment by stevekuznetsov** [comment]
```
$ du -d 1 -c -h /var/lib/jenkins/jobs/
616M	/var/lib/jenkins/jobs/origin-ci-verify-origin
648M	/var/lib/jenkins/jobs/origin-ci-steve-origin
2.4G	/var/lib/jenkins/jobs/origin-ci-build-origin
4.0G	/var/lib/jenkins/jobs/origin-ci-int-origin
282M	/var/lib/jenkins/jobs/origin-ci-build-tools
656M	/var/lib/jenkins/jobs/origin-ci-ut-origin
16K	/var/lib/jenkins/jobs/OpenShift Sample
3.8G	/var/lib/jenkins/jobs/origin-ci-cmd-origin
16K	/var/lib/jenkins/jobs/origin-ci-ci-setup
274M	/var/lib/jenkins/jobs/origin-ci-build-base-images
393M	/var/lib/jenkins/jobs/origin-ci-openshift-cns-testdrive-origin
13G	/var/lib/jenkins/jobs/
13G	total
```

**Comment by stevekuznetsov** [comment]
```
$ du -d 1 -c -h /var/lib/jenkins/jobs/origin-ci-int-origin/
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@19
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@20@tmp
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@9@tmp
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@15@tmp
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@12
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@3
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@11@tmp
24K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@2@tmp
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@12@tmp
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@6@tmp
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@9
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@19@tmp
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@13
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@14
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@10@tmp
1.2G	/var/lib/jenkins/jobs/origin-ci-int-origin/builds
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@16
20K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@7@tmp
20K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@5@tmp
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@script
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@4@tmp
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@21
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@16@tmp
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@2
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@17@tmp
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@14@tmp
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@13@tmp
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@5
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@8
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@10
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@18@tmp
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@17
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@20
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@8@tmp
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@6
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace
1.9M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@libs
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@4
4.0K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@21@tmp
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@11
40K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@tmp
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@18
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@15
128M	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@7
40K	/var/lib/jenkins/jobs/origin-ci-int-origin/workspace@3@tmp
4.0G	/var/lib/jenkins/jobs/origin-ci-int-origin/
4.0G	total
```

**Comment by stevekuznetsov** [comment]
```
$ ls /var/lib/jenkins/jobs/origin-ci-int-origin/builds/ | wc -l
1198
```

**Comment by stevekuznetsov** [comment]
Yeah so if we prune builds and workspaces we should be golden. That's what is currently taking up space.

**Comment by stevekuznetsov** [comment]
Realized our JJB configmaps did not have the old build deletion in there... so re-pushed, we should see use go down.

**Comment by stevekuznetsov** [comment]
Workspace pruning addressed by #https://github.com/openshift/release/pull/349

**Comment by kargakis** [comment]
@stevekuznetsov @csrwng fixed?

**Comment by csrwng** [comment]
yes
