### ISSUE TITLE
[ci-operator]report.go panicked when invalid dockerfile is used in build

### ISSUE THREAD

**Issue by hongkailiu** [openshift/release#8536]
Reported in [slack](https://coreos.slack.com/archives/CBN38N3MW/p1587669937233900).

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8529/rehearse-8529-pull-ci-kube-reporting-presto-release-4.3-images/3
```
--> INSTALL_PKGS="GIT 
error: build error: Unknown instruction: INSTALL_PKGS="GIT
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1704aee]
goroutine 1 [running]:
github.com/openshift/ci-tools/pkg/results.(*reporter).Report(0xc000906420, 0x1e85480, 0xc0009e8180)
	/go/src/github.com/openshift/ci-tools/pkg/results/report.go:144 +0x2fe
main.(*options).Report(0xc000227b80, 0x1e83ec0, 0xc0009e8180)
	/go/src/github.com/openshift/ci-tools/cmd/ci-operator/main.go:504 +0xf7
main.main()
	/go/src/github.com/openshift/ci-tools/cmd/ci-operator/main.go:201 +0x30e

```

**Comment by hongkailiu** [comment]
Even for successful build?
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8529/rehearse-8529-pull-ci-kube-reporting-presto-master-images/3

**Comment by hongkailiu** [comment]
reverted the PR causing it.

/close
